<a href="https://colab.research.google.com/github/Gayathri7841/AI-Learning-Journey/blob/main/LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1) Import Packages**

In [26]:
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# **2) Load Dataset**

In [2]:
from google.colab import files
uploaded=files.upload()

Saving melb_data.csv to melb_data.csv

In [3]:
df=pd.read_csv('melb_data.csv')
print(df.shape)
df.head()

(13580, 21)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

# **3) Inspection**

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  object
 20  Propertycount  13580 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 2.2+ MB

In [15]:
df.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

# **4)** **Define Target and features**

In [4]:
y=df['Price']
x=df.drop(columns=['Price'])

In [14]:
y

0        1480000.0
1        1035000.0
2        1465000.0
3         850000.0
4        1600000.0
           ...
13575    1245000.0
13576    1031000.0
13577    1170000.0
13578    2500000.0
13579    1285000.0
Name: Price, Length: 13580, dtype: float64

In [13]:
x

,Suburb,Address,Rooms,Type,Method,SellerG,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Regionname,Propertycount,SoldYear,SoldMonth,SoldDate
0,Abbotsford,85 Turner St,2,h,S,Biggin,2.5,3067.0,2.0,1.0,1.0,202.0,NaN,NaN,Yarra,Northern Metropolitan,4019.0,2016,12,3
1,Abbotsford,25 Bloomburg St,2,h,S,Biggin,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,Yarra,Northern Metropolitan,4019.0,2016,2,4
2,Abbotsford,5 Charles St,3,h,SP,Biggin,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,1900.0,Yarra,Northern Metropolitan,4019.0,2017,3,4
3,Abbotsford,40 Federation La,3,h,PI,Biggin,2.5,3067.0,3.0,2.0,1.0,94.0,NaN,NaN,Yarra,Northern Metropolitan,4019.0,2017,3,4
4,Abbotsford,55a Park St,4,h,VB,Nelson,2.5,3067.0,3.0,1.0,2.0,120.0,142.0,2014.0,Yarra,Northern Metropolitan,4019.0,2016,6,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,S,Barry,16.7,3150.0,4.0,2.0,2.0,652.0,NaN,1981.0,NaN,South-Eastern Metropolitan,7392.0,2017,8,26
13576,Williamstown,77 Merrett Dr,3,h,SP,Williams,6.8,3016.0,3.0,2.0,2.0,333.0,133.0,1995.0,NaN,Western Metropolitan,6380.0,2017,8,26
13577,Williamstown,83 Power St,3,h,S,Raine,6.8,3016.0,3.0,2.0,4.0,436.0,NaN,1997.0,NaN,Western Metropolitan,6380.0,2017,8,26
13578,Williamstown,96 Verdon St,4,h,PI,Sweeney,6.8,3016.0,4.0,1.0,5.0,866.0,157.0,1920.0,NaN,Western Metropolitan,6380.0,2017,8,26
13579,Yarraville,6 Agnes St,4,h,SP,Village,6.3,3013.0,4.0,1.0,1.0,362.0,112.0,1920.0,NaN,Western Metropolitan,6543.0,2017,8,26

In [5]:
x.drop(columns=['Lattitude','Longtitude'],axis=1,inplace=True)

In [6]:
x.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Method', 'SellerG', 'Date',
       'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car', 'Landsize',
       'BuildingArea', 'YearBuilt', 'CouncilArea', 'Regionname',
       'Propertycount'],
      dtype='object')

# **5)Feature Engineering**

In [7]:
x['Date']=pd.to_datetime(x['Date'],errors='coerce',dayfirst=True)
x['SoldYear']=  x['Date'].dt.year
x['SoldMonth']=  x['Date'].dt.month
x['SoldDate']=  x['Date'].dt.day
x.drop(columns=['Date'],axis=1,inplace=True)
x.head(3)

,Suburb,Address,Rooms,Type,Method,SellerG,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Regionname,Propertycount,SoldYear,SoldMonth,SoldDate
0,Abbotsford,85 Turner St,2,h,S,Biggin,2.5,3067.0,2.0,1.0,1.0,202.0,NaN,NaN,Yarra,Northern Metropolitan,4019.0,2016,12,3
1,Abbotsford,25 Bloomburg St,2,h,S,Biggin,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,Yarra,Northern Metropolitan,4019.0,2016,2,4
2,Abbotsford,5 Charles St,3,h,SP,Biggin,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,1900.0,Yarra,Northern Metropolitan,4019.0,2017,3,4

# **6)Seperate Numerical and Categorical data**

In [20]:
num=x.select_dtypes(include="number").columns
cat=x.select_dtypes(exclude="number").columns

In [9]:
num

,Rooms,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Propertycount,SoldYear,SoldMonth,SoldDate
0,2,2.5,3067.0,2.0,1.0,1.0,202.0,NaN,NaN,4019.0,2016,12,3
1,2,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,4019.0,2016,2,4
2,3,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,1900.0,4019.0,2017,3,4
3,3,2.5,3067.0,3.0,2.0,1.0,94.0,NaN,NaN,4019.0,2017,3,4
4,4,2.5,3067.0,3.0,1.0,2.0,120.0,142.0,2014.0,4019.0,2016,6,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,4,16.7,3150.0,4.0,2.0,2.0,652.0,NaN,1981.0,7392.0,2017,8,26
13576,3,6.8,3016.0,3.0,2.0,2.0,333.0,133.0,1995.0,6380.0,2017,8,26
13577,3,6.8,3016.0,3.0,2.0,4.0,436.0,NaN,1997.0,6380.0,2017,8,26
13578,4,6.8,3016.0,4.0,1.0,5.0,866.0,157.0,1920.0,6380.0,2017,8,26
13579,4,6.3,3013.0,4.0,1.0,1.0,362.0,112.0,1920.0,6543.0,2017,8,26

In [10]:
cat

,Suburb,Address,Type,Method,SellerG,CouncilArea,Regionname
0,Abbotsford,85 Turner St,h,S,Biggin,Yarra,Northern Metropolitan
1,Abbotsford,25 Bloomburg St,h,S,Biggin,Yarra,Northern Metropolitan
2,Abbotsford,5 Charles St,h,SP,Biggin,Yarra,Northern Metropolitan
3,Abbotsford,40 Federation La,h,PI,Biggin,Yarra,Northern Metropolitan
4,Abbotsford,55a Park St,h,VB,Nelson,Yarra,Northern Metropolitan
...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,h,S,Barry,NaN,South-Eastern Metropolitan
13576,Williamstown,77 Merrett Dr,h,SP,Williams,NaN,Western Metropolitan
13577,Williamstown,83 Power St,h,S,Raine,NaN,Western Metropolitan
13578,Williamstown,96 Verdon St,h,PI,Sweeney,NaN,Western Metropolitan
13579,Yarraville,6 Agnes St,h,SP,Village,NaN,Western Metropolitan

# **7) Preprocessing Pipeline(impute +encode + scaling)**

In [21]:
num_transformation = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaling", StandardScaler())
])

cat_transformation = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("num", num_transformation, num),
    ("cat", cat_transformation, cat)
])

# **8) Train and Test data split**

In [22]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.15, random_state=42
)

x_train = preprocessor.fit_transform(x_train)
x_test = preprocessor.transform(x_test)

# **9) Train Model**

In [23]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

# **10) Test Model**

In [24]:
y_pred = model.predict(x_test)

In [25]:
result = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

result.head(10)

      Actual     Predicted
0  2600000.0  1.712234e+06
1   620000.0  8.392900e+05
2  1000000.0  1.556566e+06
3   430000.0  8.254430e+05
4   392250.0  3.140636e+05
5   700000.0  9.535424e+05
6   439000.0  7.243200e+05
7  2236000.0  1.526541e+06
8   671000.0  5.175311e+05
9  1870000.0  1.299210e+06

# **11) Evaluate MSE and RMSE metrics**

In [28]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R² Score:", r2)
print("Train R²:", model.score(x_train, y_train))
print("Test R² :", model.score(x_test, y_test))

MAE : 470186.87599607505
MSE : 418317385797.0243
RMSE: 646774.6020036844
R² Score: -0.04370227339469146
Train R²: 0.9999587109413582
Test R² : -0.04370227339469146